-- Create users table
CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(42) PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create tweets table
CREATE TABLE IF NOT EXISTS tweets (
  id SERIAL PRIMARY KEY,
  content TEXT NOT NULL,
  user_id VARCHAR(42) REFERENCES users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
); 